wandb_version: 1

name:
  desc: null
  value: ConvMixer
experiment:
  desc: null
  value: Final
optimizer_name:
  desc: null
  value: AdamW
batch_size:
  desc: null
  value: 512
scale:
  desc: null
  value: 1.0
reprob:
  desc: null
  value: 0.2
ra_m:
  desc: null
  value: 12
ra_n:
  desc: null
  value: 2
jitter:
  desc: null
  value: 0.2
hdim:
  desc: null
  value: 256
depth:
  desc: null
  value: 8
psize:
  desc: null
  value: 2
conv_ks:
  desc: null
  value: 5
wd:
  desc: null
  value: 0.005
clip_norm:
  desc: null
  value: false
epochs:
  desc: null
  value: 150
lr_max:
  desc: null
  value: 0.05
workers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700875714.09874
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      6: 4.35.2
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
