wandb_version: 1

architecture:
  desc: null
  value: UpscaleNN
dataset:
  desc: null
  value: CIFAR-10
val_batch_size:
  desc: null
  value: 500
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.0
decay:
  desc: null
  value: 0.0
optimizer_name:
  desc: null
  value: SGD
get_optimizer_fn:
  desc: null
  value: wba_manager.get_config.<locals>.<lambda>
_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699914816.92999
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.11.1
      5: 0.15.12
      6: 4.35.0
      8:
      - 3
      - 5
      13: windows-amd64
